version: '3.9'

services:

  keycrawler:
    image: ${DOCKER_REGISTRY-}keycrawler
    build:
        context: .
        dockerfile: Dockerfile
    depends_on: 
        - hangfiredb

  hangfiredb:
    image: postgres:latest
    ports:
        - 5432:5432
    environment:
        POSTGRES_DB: Hangfire