version: '3.9'

services:

  keycrawlerwebapi:
    image: keycrawlerwebapi
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on: 
      - hangfiredb
      - keycrawlerdb
    restart: on-failure

  keycrawlergrpc:
    image: keycrawlergrpc
    build:
      context: .
      dockerfile: Dockerfile.grpc
    restart: on-failure

  envoyproxy:
    image: envoyproxy
    build:
      context: .
      dockerfile: Envoy/Dockerfile

  hangfiredb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: Hangfire
    restart: always

  keycrawlerdb:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: KeyCrawler
    restart: always