version: '3.9'

services:

  keycrawlerwebapi:
    ports:
      - 80:80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80

  keycrawlergrpc:
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080