version: '3.9'

services:

  keycrawler:
    image: ${DOCKER_REGISTRY-}keycrawler
    build:
        context: .
        dockerfile: Dockerfile
    ports: 
        - 80:80
    expose: 
        - 80
    depends_on: 
        - hangfiredb

  hangfiredb:
    image: postgres:latest
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: Hangfire