version: '3.9'

services:

  keycrawlerwebapi:
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001;http://+:5000
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/keycrawler.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  hangfiredb:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycrawlerdb:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres