version: '3.9'

services:

  keycrawlerwebapi:
    image: keycrawlerwebapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - hangfiredb
      - keycrawlerdb
    restart: on-failure

  hangfiredb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: Hangfire
    restart: always

  keycrawlerdb:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: KeyCrawler
    restart: always