version: '3.9'

services:

  keycrawlerwebapi:
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000

  keycrawlergrpc:
    ports:
      - 6000:6000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:6000

  keycrawler_frontend:
    ports:
      - 3000:3000

  envoyproxy:
    ports:
      - 6060:6060
      - 9901:9901

  hangfiredb:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycrawlerdb:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres