version: '3.9'

services:

  keycrawler:
    image: ${DOCKER_REGISTRY-}keycrawler
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - hangfiredb
    restart: on-failure

  hangfiredb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: Hangfire
    restart: always